### ISSUE TITLE
batch pool ids don't seem to be recycled

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#297]
I created a batch pool as follows:

`aztk spark cluster create --id pool1`

I deleted `pool1` via the portal, and then ran the following again:

`aztk spark cluster create --id pool1`

and I get an error message:

```
...
--------------------------------------------
The specified job already exists.
RequestId:<some long id>
Time:2017-12-20T08:40:15.3848728Z
-------------------------------------------
```
even though the portal claims the pool has been deleted. 

**Update:** the pool is still created despite the warning message above

**Comment by timotheeguerin** [comment]
The problem is aztk creates a pool and a **job** If you delete the pool through the portal, the job will remain(Though if you delete the job with the same id in the portal too it will work). You should use the command line `aztk spark cluster delete --id pool1`.

If you want to use a UI I would recommend BatchLabs(https://azure.github.io/BatchLabs) When you want to delete a pool it will check if there is a job with the same id and propose to delete it for you too.

**Comment by willferreira** [comment]
Thanks. I will use the command line to delete the pool in future
