### ISSUE TITLE
Add Spark Shuffle Service Support

### ISSUE THREAD

**Issue by jafreck** [Azure/aztk#370]
Enable shuffle service by default by setting `spark.shuffle.service.enabled true` in spark-defaults.conf.

Also, open port 7337 in container.

https://spark.apache.org/docs/latest/configuration.html#shuffle-behavior

**Comment by jiata** [comment]
why are we setting non-default configurations for spark? Shouldn't this be something we allow them to enable if they wish.

**Comment by paselem** [comment]
This is similar to the decision we made regarding the chunk size for data. It's a 'better' default for distributed spark clusters since it makes it more reliable to nodes leaving the cluster. In this case, we can rely on Spark's shuffle system to move data around and not force a re-compute if a node goes away. With our focus on low-pri nodes, I feel this is probably a good default for AZTK.

**Comment by jafreck** [comment]
Additionally, enabling the shuffle service is required for dynamic allocation. And dynamic allocation allows re-scaling of the cluster during Spark application execution.

So without the shuffle service and dynamic allocation enabled by default, resizing your cluster will only affect subsequent jobs. 

This is a very large deal for job submission mode, where the spark submits are executed immediately after the master is elected, and potentially before all workers in the cluster are up.

**Comment by jiata** [comment]
makes sense. thanks guys
