### ISSUE TITLE
Stuck at cluster create

### ISSUE THREAD

**Issue by yueguoguo** [Azure/aztk#398]
Hi,

When I tried to create a cluster with `aztk spark cluster create --id my_cluster --size 5 --vm-size standard_d2_v2 --docker-repo microsoft/mmlspark:latest`, it got stuck in the creation process (I waited for approx. 20 minutes). I went to portal and noticed that the cluster has already been created. 

I forced stop of the process with keyinterrupt and got an output log saying that it was waiting for master node. 

Any idea on this?

**Comment by timotheeguerin** [comment]
The most common reason for this to happen is the cluster wasn't created correctly, something went wrong at the boot time and the master wasn't elected. 
Can you currently ssh into your cluster?
Otherwise can you go to one of the node and check the stderr.txt in startup folder(As shown below).
![image](https://user-images.githubusercontent.com/1031227/36163190-7d9452f4-109d-11e8-9761-de8b7aafe1a4.png)

There are other files which might be of importance in the `startup/wd/logs` folder if stderr.txt doesn't contain any intresting information

**Comment by jafreck** [comment]
@yueguoguo Please note that the image you are using is not one of the supported images. For reference, see [Docker Images](https://github.com/Azure/aztk/tree/master/docker-image).

You can use a custom Docker image, but I do not believe the image you are using will work.

**Comment by yueguoguo** [comment]
@jafreck I think you are correct. When I changed the Docker image it worked. Is there a limitation on custom Docker image?

**Comment by yueguoguo** [comment]
@timotheeguerin Thanks!

**Comment by jafreck** [comment]
The documentation for custom Docker images is [here](https://github.com/Azure/aztk/tree/master/docker-image#how-do-i-use-my-own-docker-image). 

The easiest way to create a custom docker image is to build on top of one of the existing AZTK images:
```
# Your custom Dockerfile

FROM aztk/base:spark2.2.0
...
```

Let me know if you need any more assistance. I am going to close this issue now that it is resolved,
