### ISSUE TITLE
Add ability to include directory during job submission

### ISSUE THREAD

**Issue by ghendrymsft** [Azure/aztk#427]
My python is usually modular with multiple directories.  For example:

src/
  foo/
    __init__.py
    utils.py
  bar/
     __init__.py
     other_thing.py
  run.py
  __init__.py

where run.py does:
from foo import utils
from bar import other_thing
 
I want to:
aztk spark cluster submit --id=myid --name=jobname --py-files=src src/run.py

and have it keep the directory structure the same so that my imports work properly.

**Comment by ghendrymsft** [comment]
sorry, github didn't preserve the spacing when I listed out the directory structure.  Hopefully you get the idea.

**Comment by jafreck** [comment]
One suggestion here is to zip up `src` and use that as a module by adding it to your path. There is some more information on how to do this [here](https://stackoverflow.com/questions/36461054/i-cant-seem-to-get-py-files-on-spark-to-work).


In general, the `aztk spark cluster submit` is supposed to map directly to a `spark-submit`, and since `spark-submit` doesn't support specifying directories, this may be out of scope. Still, I think this would be a nice feature to have even if it isn't natively supported by Spark.

**Comment by paselem** [comment]
I agree with @jafreck on this. There are some standard patterns for spark for this scenario. I was able to get around this by doing this:

```sh
aztk spark cluster submit --id <my_cluster> --name 001 --py-files ./lib.zip ./app.py
```

You will need to make sure that any dependencies in lib.zip are satisfied on the cluster. For example, if any files in lib.zip take a dependency on a library (for example __azure__) then there are 3 ways to make sure it's addressed:

1. If your cluster is already up and running do a __cluster run__ to install the library
```sh
aztk spark cluster run --id <my_cluster> "pip install azure"
```

2. Use a custom script to run scripts on the cluster as it is booting up
pip install script:
```sh
# install azure
pip install azure
```

```yaml
custom_scripts:
    - script: custom-scripts/pip_install.sh
      runOn: all-nodes
```

3. Finally you can use your own docker container that includes any/all dependencies.

**Comment by paselem** [comment]
Closing issue since I feel this is a Spark related workflow and has existing solutions/workarounds today already.
