### ISSUE TITLE
Issue Calling "aztk spark init"

### ISSUE THREAD

**Issue by mikecoe** [Azure/aztk#429]
Hi

I am trying to get aztk up and running on my windows environment but am having issues.  

I have ran through the following commands which all completed successfully:
git clone https://www.github.com/azure/aztk
pip3 install -r requirements.txt
pip3 install -e .

however when I try and call 
aztk spark init

I get the following output and no .aztk directory is created:
Traceback (most recent call last):
  File "/usr/bin/aztk", line 11, in <module>
    load_entry_point('aztk', 'console_scripts', 'aztk')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/cygdrive/c/Git/aztk/cli/entrypoint.py", line 42
    def setup_common_args(parser: argparse.ArgumentParser):
                                ^
SyntaxError: invalid syntax

Please can you advise?

Many Thanks
Mike

**Comment by timotheeguerin** [comment]
Seems like you are using python 2.7 can you try with 3.5 and above

**Comment by jafreck** [comment]
Like Tim said, the error indicates that your system default version of python is 2.7, while AZTK requires 3.5 or above.

There are a couple of options here:
- Switch the system default python version. If you need additional information on this, let me know what OS you are using.
- Use AZTK in a virtual environment. If you are using python 3.6, you can run `python3 -m venv /path/to/new/virtual/environment`. On python 3.5, you can run `pyvenv /path/to/new/virtual/environment`. More information on virtual environments can be found [here](https://docs.python.org/3/library/venv.html).

I'm going to close this issue since I believe it is not an AZTK bug, but please let us know if you continue to run into issues related to this or anything else.
