### ISSUE TITLE
Spark spill/shuffle mount point incorrect

### ISSUE THREAD

**Issue by jaley** [Azure/aztk#453]
It seems `/mnt/batch` is not the right place to be using for `spark.local.dir`, as this is on the root volume in the Docker contain, which means the data is written to `/var/lib/docker/..` on the host machine, and that's mounted on `/dev/sda1`, which is only 30GB.

Changing to `/mnt/batch/tasks/spark-local` works well for me (it'll create a directory within tasks), as this is mounted on `/dev/sdb1` on the host machine, which is much larger.

Further, setting this path with the `spark.local.dir` Spark conf parameter seems to generate a warning in the driver application logs. Apparently Spark recommends setting it with the `SPARK_LOCAL_DIRS` environment variable in `spark-env.sh` instead. I believe this is because that setting should really be under the control of the cluster manager, which won't be able to mess with the user's spark-defaults. It appears to work either way on aztk, but it'll clean up a warning.

**Comment by jafreck** [comment]
Since [3e42e25](https://github.com/Azure/aztk/commit/3e42e25ebad54d1241f3ed092887eb4f18ec57b4), `spark.local.dir` has been set to `/mnt/batch/tasks/`.

We can change it to `/mnt/batch/tasks/spark-local` so that the directory is a little cleaner, however, the shuffle point seems to be on the right partition (unless I'm misunderstanding you or missing something).

**Comment by jafreck** [comment]
Closing since I believe this is no longer and issue.
