### ISSUE TITLE
Hadoop fs path not able to read wasb path

### ISSUE THREAD

**Issue by k-pratik** [Azure/aztk#500]
I have following code inside my spark job to check if file exist
`
val conf = spark.sparkContext.hadoopConfiguration
val fs = org.apache.hadoop.fs.FileSystem.get(conf)
return fs.exists(new org.apache.hadoop.fs.Path(filePath))
`
I get following error when trying to submit my job:

`Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS: wasb://container@test.blob.core.windows.net/reports/lastRun, expected: file:///`

I have modified my core-site.xml

```
<property>
  <name>fs.AbstractFileSystem.wasb.Impl</name>
  <value>org.apache.hadoop.fs.azure.Wasb</value>
</property>
<property>
  <name>fs.azure.account.key.test.blob.core.windows.net</name>
 <value>vAe</value>
</property>
```

Could you please let me know if I am missing something

**Comment by jafreck** [comment]
@k-pratik After investigating, this issue is because the default filesystem is or.apache.hadoop.fs.LocalFileSystem.

Closing since this is not an AZTK bug.

**Comment by k-pratik** [comment]
@jafreck Found this in spark-default.conf
```
# Note: Aztk pre-loads wasb jars, so loading is not necessary
spark.jars                      /home/spark-current/jars/azure-storage-2.0.0.jar,/home/spark-current/jars/hadoop-azure-2.7.3.jar
```
Do i still need to download jar in jars folder?

Also did not understand last comment, what I need to do i order to make it work?

**Comment by jafreck** [comment]
You do not need to add anything in `spark-defaults.conf`. 

The reason your code is not working is not because WASB is set up incorrectly. The code you shared only works for the default filesystem path (`file:///`). You need to update your code or change the hadoop configuration to make WASB the default filesystem. 

I don't think this is an aztk bug, but if you have evidence otherwise, please open another issue.
