### ISSUE TITLE
"Accept header absent and forced to application/json" spam

### ISSUE THREAD

**Issue by jaley** [Azure/aztk#608]
Since updating to 0.8.0, I'm getting a lot of warnings printed to stderr about a missing `Accept` header in the REST requests. Seems to be coming from the Azure REST API, [here](https://github.com/Azure/msrest-for-python/blob/master/msrest/service_client.py#L262).

This fills up our logs on VSTS for long-running jobs.

**Comment by timotheeguerin** [comment]
This sounds like msrest was updated recently to this, we don't have a direct dependency on it, I guess the issue is with some of the sdk that is not specifiing the header correctly. 

In the meantime you can force msrest to be at a previous version or suppress the warning

**Comment by jafreck** [comment]
[We already suppress warning from `msrestazure`](https://github.com/Azure/aztk/blob/7d7a814c5018ae337731936f6738f32b20350a61/aztk/__init__.py#L7), should we do the same thing for `msrest`?

Since the issue is arising because of a transitive dependency, we really shouldn't surface any logging I feel.

**Comment by timotheeguerin** [comment]
I looked at their code and it seems like the logger name is the filename not msrest azure so I think it might be pretty hard to suppress
