### ISSUE TITLE
Low priority nodes spin up as "offline" in a mixed custer

### ISSUE THREAD

**Issue by annisele** [Azure/aztk#662]
```
Cluster         myclustertest4
------------------------------------------
State:          active
Node Size:      standard_d2_v2
Nodes:          2
| Dedicated:    1
| Low priority: 1

|               Nodes                |        State        |        IP:Port       | Dedicated  |  Master  |
|------------------------------------|---------------------|----------------------|------------|----------|
| tvm-3623504638_1-20180920t144716z  |        idle         |  52.177.223.93:50000 |     *      |    *     |
|tvm-3623504638_2-20180920t144726z-p |       offline       |  40.70.73.226:50000  |            |          |
```

this only happens for mixed nodes clusters.

**Comment by jafreck** [comment]
This is expected, default behavior for aztk version 0.8.0 and 0.8.1 so I'm going to close this issue.

A little bit of backstory here: nodes were set to offline with the intention of blocking scheduling on them.  This way the Spark driver would only run on a dedicated node (or the master if `scheduling_target` was set to `master`). This feature has been rolled back in the latest version (0.9.0), though, because there were issues related to preemption recovery for offline low-priority nodes. 

Let me know if you have any questions about this.
