### ISSUE TITLE
Requested number of low priority VMs are not provisioned.

### ISSUE THREAD

**Issue by ana1993** [Azure/aztk#697]
I tried provisioning a cluster with 2 dedicated and 18 low priority E16 VMs in Central India region. It succeeded on the first attempt and worked perfectly. But when I tried it again couple of days later , I saw that only the dedicated ones have been provisioned and no low priority VMs came up even though the state of the cluster went to steady.

I am using a custom spark image. The issue is intermittent. 
Am I missing something.

**Comment by jafreck** [comment]
Azure low priority VMs are not guaranteed to be allocated. Aztk clusters are marked as steady once the Spark master has been selected and is up. There is no guarentee that all VMs are available when the cluster goes to steady. Nodes that come up later will join the Spark cluster dynamically.

The behavior you are describing is expected when low-pri VMs. Low priority VMs may be preempted any time after allocation as well.

Since this is expected, I am going to close the issue, but please feel free to reach out if you have more questions.
